language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.5
  - 1.6
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

coveralls: true

before_install:
  - julia -e 'import Pkg; Pkg.pkg"add https://github.com/anowacki/Geodesics.jl https://github.com/anowacki/Seis.jl https://github.com/anowacki/StationXML.jl"'
