language: julia
os:
  - osx
  - linux
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'VERSION >= v"0.7" && import Pkg; cd(Pkg.dir("SAC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
